### ISSUE TITLE
Update PyPi package!

### ISSUE THREAD

**Issue by jedie** [aldryn/aldryn-boilerplates#25]
https://pypi.org/project/aldryn-boilerplates/ has only v0.7.5 from Feb 28, 2017

So Django v1.11 compatibility is not included, see: #24 :(

**Comment by benzkji** [comment]
Please. It breaks Django 1.11 compatibility for most of aldryn packages, even if one doesnt use boilerplates! (aldryn-search, in my case).

**Comment by jedie** [comment]
ping

**Comment by jedie** [comment]
ping

**Comment by filwaitman** [comment]
@jedie versions 0.7.7 released on PyPI
